"""Log template mining — a from-scratch Drain implementation.

The problem: a test run produces thousands of log lines, but they are generated by
only a few dozen `printf` statements. Analysis wants the *statements*, not the
lines. Turning this:

    assoc resp status=0 aid=19 bssid=be:14:66:79:d2:d6 elapsed_ms=16
    assoc resp status=0 aid=7  bssid=4a:ca:57:74:63:67 elapsed_ms=22

into this:

    assoc resp status=<*> aid=<*> bssid=<*> elapsed_ms=<*>    (hits: 2)

is the foundation of every automated log analysis technique. Once lines are
templates, you can count them, diff two runs, feed the histogram to a clustering
model, or hand an LLM 40 templates instead of 4,000 lines.

Why Drain specifically, and why implemented rather than imported
---------------------------------------------------------------
Drain (He et al., ICWS 2017) builds a **fixed-depth parse tree**, which makes it
O(1)-ish per line instead of comparing each line against every known template. The
tree is keyed on properties that are cheap and stable:

    level 1: token count      (lines of different length are never the same template)
    level 2: first token      (the log statement's leading word rarely varies)
    level 3: second token
    leaf   : candidate templates, compared by token-wise similarity

It is implemented here rather than pip-installing `drain3` because the whole
algorithm is about 150 readable lines, and the point of this project is to
understand the technique. In production the answer flips and you take the library.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

#: Wildcard marker for a variable position.
PARAM = "<*>"

#: Token-similarity threshold for joining an existing template. Drain's paper
#: suggests 0.4-0.5; 0.5 is used here because wireless logs are short, so a lower
#: threshold over-merges genuinely different statements.
SIMILARITY_THRESHOLD = 0.5

#: Maximum children per tree node before new ones collapse into a catch-all. Bounds
#: memory on pathological input — an attacker-controlled log must not be able to
#: grow the tree without limit.
MAX_CHILDREN = 100

#: Tree depth. Drain's paper uses 4 (two token levels plus root and leaf).
DEPTH = 4

#: Patterns pre-masked before tokenising. This is where domain knowledge enters the
#: algorithm: a MAC address or a hex nonce is *always* a variable, and masking it up
#: front prevents the miner from creating a separate template per BSSID — which is
#: the single most common way naive log mining produces thousands of useless
#: "templates" that are really one statement.
MASKS: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"\b(?:[0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}\b"), "<MAC>"),
    (re.compile(r"\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b"), "<IP>"),
    (re.compile(r"\b0x[0-9a-fA-F]+\b"), "<HEX>"),
    (re.compile(r"\b[0-9a-fA-F]{16,}\b"), "<HEX>"),
    (re.compile(r"\b\d{4}-\d{2}-\d{2}T[\d:.]+Z?\b"), "<TIME>"),
    (re.compile(r"\b\d+\.\d+\b"), "<FLOAT>"),
    (re.compile(r"\b\d+\b"), "<NUM>"),
)


def mask(text: str) -> str:
    """Replace obviously-variable substrings before tokenising."""
    for pattern, replacement in MASKS:
        text = pattern.sub(replacement, text)
    return text


def tokenise(message: str) -> list[str]:
    return mask(message).split()


@dataclass
class Template:
    id: int
    tokens: list[str]
    hits: int = 0
    examples: list[str] = field(default_factory=list)

    @property
    def text(self) -> str:
        return " ".join(self.tokens)

    @property
    def param_count(self) -> int:
        return sum(1 for t in self.tokens if t == PARAM)

    def add_example(self, raw: str, limit: int = 3) -> None:
        if len(self.examples) < limit:
            self.examples.append(raw)

    def __str__(self) -> str:
        return f"T{self.id:<3} x{self.hits:<5} {self.text}"


def similarity(a: list[str], b: list[str]) -> float:
    """Fraction of positions where two equal-length token lists agree.

    Positions already marked `<*>` count as matching, which is what allows a
    template to keep generalising as it absorbs more lines.
    """
    if not a or len(a) != len(b):
        return 0.0
    # strict=True: the caller guarantees equal length (it checks len() first),
    # so a mismatch here is a bug, not something to silently truncate.
    same = sum(1 for x, y in zip(a, b, strict=True) if x in (y, PARAM))
    return same / len(a)


class _Node:
    __slots__ = ("children", "templates")

    def __init__(self) -> None:
        self.children: dict[str, _Node] = {}
        self.templates: list[Template] = []


class DrainMiner:
    """Fixed-depth-tree log template miner."""

    def __init__(
        self,
        similarity_threshold: float = SIMILARITY_THRESHOLD,
        depth: int = DEPTH,
        max_children: int = MAX_CHILDREN,
    ) -> None:
        self.threshold = similarity_threshold
        # Depth counts root and leaf, so the number of token levels is depth - 2.
        self.token_levels = max(depth - 2, 1)
        self.max_children = max_children
        self._root = _Node()
        self._templates: dict[int, Template] = {}
        self._next_id = 1

    # ---- tree navigation ----

    def _leaf_for(self, tokens: list[str], *, create: bool) -> _Node | None:
        node = self._root
        # Level 1: token count.
        key = str(len(tokens))
        if key not in node.children:
            if not create:
                return None
            node.children[key] = _Node()
        node = node.children[key]

        # Levels 2..n: leading tokens. A token that was masked into a wildcard is
        # not a usable tree key (it would split identical statements apart), so it
        # routes into a shared "*" branch.
        for i in range(min(self.token_levels, len(tokens))):
            token = tokens[i]
            key = "*" if token.startswith("<") and token.endswith(">") else token
            if key not in node.children:
                if not create:
                    return node if node.templates else None
                if len(node.children) >= self.max_children:
                    key = "*"
                    node.children.setdefault(key, _Node())
                else:
                    node.children[key] = _Node()
            node = node.children[key]
        return node

    # ---- public API ----

    def add(self, message: str) -> Template:
        """Add one log message, returning the template it belongs to."""
        tokens = tokenise(message)
        leaf = self._leaf_for(tokens, create=True)
        assert leaf is not None

        best: Template | None = None
        best_score = -1.0
        for candidate in leaf.templates:
            score = similarity(candidate.tokens, tokens)
            if score > best_score:
                best, best_score = candidate, score

        if best is not None and best_score >= self.threshold:
            # Merge: positions that disagree become wildcards. This is how a
            # template generalises over time rather than being fixed on first sight.
            # strict=False on purpose: the max_children catch-all branch can hold
            # templates of differing token counts, so the shorter list bounds the
            # merge rather than raising.
            for i, (existing, incoming) in enumerate(
                zip(best.tokens, tokens, strict=False)
            ):
                if existing != incoming and existing != PARAM:
                    best.tokens[i] = PARAM
            best.hits += 1
            best.add_example(message)
            return best

        template = Template(id=self._next_id, tokens=list(tokens), hits=1)
        template.add_example(message)
        self._next_id += 1
        leaf.templates.append(template)
        self._templates[template.id] = template
        return template

    def add_all(self, messages: list[str]) -> list[Template]:
        return [self.add(m) for m in messages]

    @property
    def templates(self) -> list[Template]:
        return sorted(self._templates.values(), key=lambda t: (-t.hits, t.id))

    def match(self, message: str) -> Template | None:
        """Find the template for a message without adding it."""
        tokens = tokenise(message)
        leaf = self._leaf_for(tokens, create=False)
        if leaf is None:
            return None
        best: Template | None = None
        best_score = -1.0
        for candidate in leaf.templates:
            score = similarity(candidate.tokens, tokens)
            if score > best_score:
                best, best_score = candidate, score
        return best if best and best_score >= self.threshold else None

    def histogram(self, messages: list[str]) -> dict[int, int]:
        """Template-id -> count for a set of messages.

        This vector is the feature representation the ML layer consumes: two runs
        that failed the same way produce similar histograms, and that is what makes
        failure clustering work.
        """
        counts: dict[int, int] = {}
        for message in messages:
            template = self.match(message)
            if template:
                counts[template.id] = counts.get(template.id, 0) + 1
        return counts

    def compression_ratio(self, total_lines: int) -> float:
        """How much the log collapsed. 0.99 means 4,000 lines became 40 templates."""
        if total_lines <= 0:
            return 0.0
        return 1.0 - (len(self._templates) / total_lines)

    def report(self, limit: int = 40) -> str:
        lines = [f"{len(self._templates)} templates from "
                 f"{sum(t.hits for t in self._templates.values())} lines"]
        for template in self.templates[:limit]:
            lines.append(f"  {template}")
        return "\n".join(lines)


def mine_files(paths: list[str]) -> tuple[DrainMiner, int]:
    """Mine several log files with one shared miner. Returns (miner, lines seen)."""
    from airframe.logs.parse import parse_file

    miner = DrainMiner()
    total = 0
    for path in paths:
        for line in parse_file(path):
            miner.add(line.message)
            total += 1
    return miner, total


def _main() -> int:
    import argparse
    import glob

    ap = argparse.ArgumentParser(description="mine log templates")
    ap.add_argument("logs", nargs="+", help="log files (globs allowed)")
    ap.add_argument("--limit", type=int, default=40)
    args = ap.parse_args()

    paths: list[str] = []
    for pattern in args.logs:
        paths.extend(glob.glob(pattern) or [pattern])

    miner, total = mine_files(paths)
    print(f"files: {len(paths)}   lines: {total}")
    print(f"templates: {len(miner.templates)}")
    print(f"compression: {miner.compression_ratio(total):.2%}\n")
    print(miner.report(args.limit))
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
